name: Build Cross-Platform App

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller gdown
      
      - name: Install gdown
        run: pip install gdown

      - name: Download backend data from Google Drive
        shell: bash
        env:
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        run: |
          mkdir -p backend
          gdown "https://docs.google.com/uc?export=download&id=${DRIVE_FOLDER_ID}" --fuzzy -O backend/backend.tar.gz
          file backend/backend.tar.gz
          tar -xzf backend/backend.tar.gz
          rm backend/backend.tar.gz
          
      - name: Build standalone executable
        shell: bash
        run: |
          pyinstaller \
            --name=Divergency \
            --windowed \
            --add-data=backend/AllSpecies:AllSpecies \
            --add-data=backend/Superposed:Superposed \
            --add-data=backend/images:images \
            --add-data=backend/node_clusters.json:node_clusters.json \
            --add-data=backend/allspecies_db:allspecies_db \
            --add-data=backend/data.json:data.json \
            --hidden-import=flask.cli \
            flaskrun.py

      - name: Create macOS DMG
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          hdiutil create \
            dist/Divergency.dmg \
            -volname "Divergency" \
            -srcfolder dist/Divergency.app \
            -ov -format UDZO

      # Windows: wrap the .exe in an NSIS installer
      - name: Create Windows installer
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          makensis -DOUTPUT_EXE="dist\Divergency.exe" installer.nsi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-bundle
          path: |
            dist/*.dmg
            dist/*-Setup.exe
